# Generated by Django 6.0 on 2026-03-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "verbose_name": "Employee Profile (ປະຫວັດພະນັກງານ)",
                "verbose_name_plural": "Employee Profiles (ປະຫວັດພະນັກງານ)",
            },
        ),
        migrations.AlterModelOptions(
            name="hourlyraterole",
            options={
                "verbose_name": "Hourly Rate Role (ຕຳແໜ່ງ/ອັດຕາຄ່າຈ້າງ)",
                "verbose_name_plural": "Hourly Rate Roles (ຕຳແໜ່ງ/ອັດຕາຄ່າຈ້າງ)",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollsummary",
            options={
                "verbose_name": "Payroll Summary (ສະຫຼຸບເງິນເດືອນ)",
                "verbose_name_plural": "Payroll Summaries (ສະຫຼຸບເງິນເດືອນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="timesheet",
            options={
                "ordering": ["-date"],
                "verbose_name": "Timesheet (ບັນທຶກຊົ່ວໂມງເຮັດວຽກ)",
                "verbose_name_plural": "Timesheets (ບັນທຶກຊົ່ວໂມງເຮັດວຽກ)",
            },
        ),
    ]
