# Generated by Django 6.0 on 2026-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="education_background",
            field=models.CharField(
                blank=True,
                help_text="ຮຽນຈົບມາແຕ່ໃສ (e.g., ມະຫາວິທະຍາໄລ ແຫ່ງຊາດລາວ - ສາຂາພາສາອັງກິດ)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="previous_workplace",
            field=models.CharField(
                blank=True,
                help_text="ສອນຢູ່ໃສ / ເຄີຍສອນຢູ່ໃສ (e.g., ໂຮງຮຽນ ABC - ຄູສອນພາສາອັງກິດ)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="ຮູບພາບອາຈານ (Profile Photo)",
                null=True,
                upload_to="employee_profiles/",
            ),
        ),
    ]
