# Generated by Django 6.0.3 on 2026-04-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_employeeprofile_education_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="ອາຍຸ (ປີ)", null=True, verbose_name="ອາຍຸ"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="full_name_en",
            field=models.CharField(
                blank=True,
                help_text="Full Name in English",
                max_length=255,
                null=True,
                verbose_name="ຊື່ນາມສະກຸນ (ອັງກິດ)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="full_name_lo",
            field=models.CharField(
                blank=True,
                help_text="ຊື່ນາມສະກຸນເປັນພາສາລາວ",
                max_length=255,
                null=True,
                verbose_name="ຊື່ນາມສະກຸນ (ລາວ)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="nickname_en",
            field=models.CharField(
                blank=True,
                help_text="Nickname in English",
                max_length=100,
                null=True,
                verbose_name="ຊື່ຫລ້ິນ (ອັງກິດ)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="nickname_lo",
            field=models.CharField(
                blank=True,
                help_text="ຊື່ຫລ້ິນເປັນພາສາລາວ",
                max_length=100,
                null=True,
                verbose_name="ຊື່ຫລ້ິນ (ລາວ)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="work_experience",
            field=models.TextField(
                blank=True,
                help_text="ປະສົບການ ແລະ ທັກສະການສອນ",
                null=True,
                verbose_name="ປະສົບການເຮັດວຽກ",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="education_background",
            field=models.TextField(
                blank=True,
                help_text="ຮຽນຈົບມາແຕ່ໃສ (e.g., ມະຫາວິທະຍາໄລ ແຫ່ງຊາດລາວ - ສາຂາພາສາອັງກິດ)",
                null=True,
                verbose_name="ປະຫວັດການສຶກສາ",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="previous_workplace",
            field=models.TextField(
                blank=True,
                help_text="ສອນຢູ່ໃສ / ເຄີຍສອນຢູ່ໃສ (e.g., ໂຮງຮຽນ ABC - ຄູສອນພາສາອັງກິດ)",
                null=True,
                verbose_name="ບ່ອນເຮັດວຽກປະຈຸບັນ",
            ),
        ),
    ]
