# Generated by Django 6.0.3 on 2026-04-24 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="ຫົວຂໍ້")),
                ("message", models.TextField(verbose_name="ຂໍ້ຄວາມ")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="popups/",
                        verbose_name="ຮູບພາບປະກອບ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ເປີດນຳໃຊ້"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="popup_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ຜູ້ປົກຄອງທີ່ຕ້ອງການສົ່ງໃຫ້ (ປະຫວ່າງໄວ້ເພື່ອສົ່ງໃຫ້ທຸກຄົນ)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Popup Message (ຂໍ້ຄວາມປ໊ອບອັບ)",
                "verbose_name_plural": "Popup Messages (ຂໍ້ຄວາມປ໊ອບອັບ)",
                "ordering": ["-created_at"],
            },
        ),
    ]
