# Generated by Django 6.0.3 on 2026-04-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Announcement (ແຈ້ງການ)",
                "verbose_name_plural": "Announcements (ແຈ້ງການ)",
            },
        ),
        migrations.CreateModel(
            name="NewsActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="news_activities/")),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "News & Activity (ຂ່າວສານ ແລະ ກິດຈະກຳ)",
                "verbose_name_plural": "News & Activities (ຂ່າວສານ ແລະ ກິດຈະກຳ)",
            },
        ),
        migrations.CreateModel(
            name="OrgChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ຜັງອົງກອນ (Organization Chart)", max_length=255
                    ),
                ),
                ("image", models.ImageField(upload_to="org_chart/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Chart (ຜັງອົງກອນ)",
                "verbose_name_plural": "Organization Chart (ຜັງອົງກອນ)",
            },
        ),
        migrations.CreateModel(
            name="SchoolHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ປະຫວັດຂອງໂຮງຮຽນ (History)", max_length=255
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="school_info/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School History (ປະຫວັດໂຮງຮຽນ)",
                "verbose_name_plural": "School History (ປະຫວັດໂຮງຮຽນ)",
            },
        ),
    ]
