# Generated by Django 6.0 on 2026-03-23 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="e.g., Lesson Understanding", max_length=255
                    ),
                ),
                (
                    "name_lo",
                    models.CharField(
                        blank=True,
                        help_text="e.g., ຄວາມເຂົ້າໃຈໃນການຮຽນ",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., ປະເມີນພຶດຕິກຳ I",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateField(auto_now_add=True)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("general_remarks", models.TextField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="academics.enrollment",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        help_text="Professor/Teacher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "Outstanding (ດີເດັ່ນ)"),
                            (4, "Excellent (ດີຫລາຍ)"),
                            (3, "Very Good (ດີ)"),
                            (2, "Average (ປານກາງ)"),
                            (1, "Below Average (ຕ່ຳກວ່າເກນ)"),
                        ],
                        help_text="Score from 1 to 5",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="academics.assessment",
                    ),
                ),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluated_details",
                        to="academics.assessmentcriteria",
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment", "criteria")},
            },
        ),
    ]
