# Generated by Django 6.0 on 2026-03-23 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_assessmentcriteria_assessment_assessmentdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="TuitionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(help_text="MM/YYYY e.g., 04/2026", max_length=7),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="ຈຳນວນເງິນຄ່າຮຽນ (ເຊັ່ນ: 500,000 ກີບ)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Paid (ຈ່າຍແລ້ວ)"),
                            ("U", "Unpaid (ຍັງບໍ່ຈ່າຍ)"),
                            ("T", "Partial (ຈ່າຍແລ້ວບາງສ່ວນ)"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_fees",
                        to="academics.enrollment",
                    ),
                ),
            ],
        ),
    ]
