# Generated by Django 6.0 on 2026-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_tuitionfee"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number (e.g., 020 96769512)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="ID STUDENT (e.g., 00601)",
                max_length=50,
                null=True,
            ),
        ),
    ]
