# Generated by Django 6.0 on 2026-03-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_student_phone_number_student_student_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "verbose_name": "Assessment (ການປະເມີນຜົນ)",
                "verbose_name_plural": "Assessments (ແບບປະເມີນຜົນການຮຽນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentcriteria",
            options={
                "ordering": ["order"],
                "verbose_name": "Assessment Criteria (ຫົວຂໍ້ປະເມີນ)",
                "verbose_name_plural": "Assessment Criterias (ຫົວຂໍ້ປະເມີນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentdetail",
            options={
                "verbose_name": "Assessment Detail (ລາຍລະອຽດປະເມີນ)",
                "verbose_name_plural": "Assessment Details (ລາຍລະອຽດປະເມີນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="classschedule",
            options={
                "verbose_name": "Class Schedule (ຕາຕະລາງຮຽນ)",
                "verbose_name_plural": "Class Schedules (ຕາຕະລາງຮຽນທັງໝົດ)",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "verbose_name": "Course (ຫຼັກສູດ/ປຶ້ມ)",
                "verbose_name_plural": "Courses (ລາຍການຫຼັກສູດ)",
            },
        ),
        migrations.AlterModelOptions(
            name="dailychecklist",
            options={
                "ordering": ["date"],
                "verbose_name": "Daily Checklist (ປຶ້ມຕິດຕາມປະຈຳວັນ)",
                "verbose_name_plural": "Daily Checklists (ປຶ້ມຕິດຕາມປະຈຳວັນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Enrollment (ການລົງທະບຽນຮຽນ)",
                "verbose_name_plural": "Enrollments (ການລົງທະບຽນຮຽນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "Student (ນັກຮຽນ)",
                "verbose_name_plural": "Students (ລາຍຊື່ນັກຮຽນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="tuitionfee",
            options={
                "verbose_name": "Tuition Fee (ຄ່າຮຽນ)",
                "verbose_name_plural": "Tuition Fees (ບັນທຶກສະຖານະຈ່າຍຄ່າຮຽນ)",
            },
        ),
    ]
