# Generated by Django 6.0 on 2026-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="listening_remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Listening Skill"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_remark",
            field=models.TextField(blank=True, null=True, verbose_name="Reading Skill"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="speaking_remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Speaking Skill"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="writing_remark",
            field=models.TextField(blank=True, null=True, verbose_name="Writing Skill"),
        ),
    ]
