# Generated by Django 6.0 on 2026-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_assessment_listening_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="full_name_lo",
            field=models.CharField(
                blank=True,
                help_text="ຊື່ແທ້ ນາມສະກຸນ ເປັນພາສາລາວ (e.g., ນາງ ມຸກຕຸລາ ເທບປັນຍາ)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="nick_name_lo",
            field=models.CharField(
                blank=True,
                help_text="ຊື່ຫຼິ້ນ ເປັນພາສາລາວ (e.g., ແມວ)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="ຮູບພາບໂປຟາຍນັກຮຽນ (Profile Photo)",
                null=True,
                upload_to="student_profiles/",
            ),
        ),
    ]
