# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_student_full_name_lo_student_nick_name_lo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="MM/YYYY e.g., 03/2026",
                        max_length=7,
                        verbose_name="ເດືອນ",
                    ),
                ),
                (
                    "monthly_test",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ຄະແນນເສັງ — ສູງສຸດ 50 ຈຸດ",
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນເສັງ (Monthly Test /50)",
                    ),
                ),
                (
                    "exercise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ຄະແນນການຝຶກ/ຊ້ອມ — ສູງສຸດ 20 ຈຸດ",
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນຊ້ອມ / Exercise (/20)",
                    ),
                ),
                (
                    "attendance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ຄະແນນການເຂົ້າຮຽນ — ສູງສຸດ 20 ຈຸດ",
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນການເຂົ້າຮຽນ / Attendance (/20)",
                    ),
                ),
                (
                    "engagement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ຄະແນນການມີສ່ວນຮ່ວມ — ສູງສຸດ 10 ຈຸດ",
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນການມີສ່ວນຮ່ວມ / Engagement (/10)",
                    ),
                ),
                (
                    "activities_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Exercise + Attendance + Engagement",
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນກິດຈະກຳລວມ (/50)",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ຄະແນນລວມ (/100)",
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        help_text="A / B+ / C+ / D / F",
                        max_length=5,
                        null=True,
                        verbose_name="Letter Grade",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="ໝາຍເຫດ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_scores",
                        to="academics.enrollment",
                        verbose_name="ນັກຮຽນ / ຫ້ອງ",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_scores_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ຜູ້ປ້ອນຄະແນນ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Score (ຄະແນນປະຈຳເດືອນ)",
                "verbose_name_plural": "Monthly Scores (ຄະແນນປະຈຳເດືອນທັງໝົດ)",
                "ordering": ["-month", "enrollment__student__full_name"],
                "unique_together": {("enrollment", "month")},
            },
        ),
    ]
