# Generated by Django 6.0.3 on 2026-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_monthly_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="letter_grade",
            field=models.CharField(
                blank=True, help_text="A / B+ / C+ / D / F", max_length=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="score_activity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ສູງສຸດ 30 ຄະແນນ (30%)",
                max_digits=5,
                null=True,
                verbose_name="ACTIVITY / ກິດຈະກຳ (/30)",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="score_attendance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ສູງສຸດ 20 ຄະແນນ (20%)",
                max_digits=5,
                null=True,
                verbose_name="ATTENDANCE / ເຂົ້າຮຽນ (/20)",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="score_exercise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ສູງສຸດ 20 ຄະແນນ (20%)",
                max_digits=5,
                null=True,
                verbose_name="Exercise / Assignment (/20)",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="score_quiz",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ສູງສຸດ 30 ຄະແນນ (30%)",
                max_digits=5,
                null=True,
                verbose_name="QUIZ / Monthly Test (/30)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyscore",
            name="activities_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Activity(30) + Attendance(20) + Exercise(20) = 70",
                max_digits=5,
                null=True,
                verbose_name="ຄະແນນ 3 ໝວດລວມ (/70)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyscore",
            name="attendance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ຄະແນນການເຂົ້າຮຽນ — ສູງສຸດ 20 ຄະແນນ (20%)",
                max_digits=5,
                null=True,
                verbose_name="ATTENDANCE / ເຂົ້າຮຽນ (/20)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyscore",
            name="engagement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ຄະແນນກິດຈະກຳ — ສູງສຸດ 30 ຄະແນນ (30%)",
                max_digits=5,
                null=True,
                verbose_name="ACTIVITY / ກິດຈະກຳ (/30)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyscore",
            name="exercise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ຄະແນນການຝຶກ/ວຽກ — ສູງສຸດ 20 ຄະແນນ (20%)",
                max_digits=5,
                null=True,
                verbose_name="Exercise / Assignment (/20)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyscore",
            name="monthly_test",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ຄະແນນ Quiz — ສູງສຸດ 30 ຄະແນນ (30%)",
                max_digits=5,
                null=True,
                verbose_name="QUIZ / Monthly Test (/30)",
            ),
        ),
    ]
