# Generated by Django 6.0.3 on 2026-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_add_score_fields_to_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="total_hours_per_month",
            field=models.IntegerField(
                default=16, help_text="Standard hours (16 or 17 based on month)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="class_type",
            field=models.CharField(
                choices=[("WD", "Weekday (ຈັນ-ພະຫັດ)"), ("WN", "Weekend (ເສົາ-ອາທິດ)")],
                default="WD",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teaching_days",
            field=models.CharField(
                default="Mon-Thu", help_text="e.g., Mon-Thu or Sat-Sun", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="time_slot",
            field=models.CharField(
                help_text="e.g., 05:30 - 06:30 PM or 10:00 - 12:00 AM", max_length=100
            ),
        ),
    ]
