# Generated by Django 6.0.3 on 2026-04-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_classschedule_total_hours_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
