# Generated by Django 6.0.3 on 2026-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_course_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "ordering": ["-evaluation_date", "-id"],
                "verbose_name": "Assessment (ການປະເມີນຜົນ)",
                "verbose_name_plural": "Assessments (ແບບປະເມີນຜົນການຮຽນ)",
            },
        ),
        migrations.AlterModelOptions(
            name="tuitionfee",
            options={
                "ordering": ["-month", "-id"],
                "verbose_name": "Tuition Fee (ຄ່າຮຽນ)",
                "verbose_name_plural": "Tuition Fees (ບັນທຶກສະຖານະຈ່າຍຄ່າຮຽນ)",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Course Thumbnail Image",
                null=True,
                upload_to="courses/",
            ),
        ),
    ]
